[program:smp1sampang-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php8.3 /home/smp1sampang/web/smp1sampang.sch.id/public_html/artisan queue:work --sleep=3 --tries=3 --timeout=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=smp1sampang
numprocs=1
redirect_stderr=true
stdout_logfile=/home/smp1sampang/web/smp1sampang.sch.id/public_html/storage/logs/worker.log
stopwaitsecs=3600
